teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - christinaharter
      - jwagantall
      - minyu66
      - thelinuxfoundation
  - name: compact-admins
    maintainers:
      - chrisferry
    members:
      - lcarvalho-shielded
  - name: compact-maintainers
    maintainers:
      - kmillikin
    members:
      - bobblessinghartley
      - dybvig
      - JosephDenman
      - leszek-shielded
      - pataei
  - name: compact-triage
    maintainers:
      - kmillikin
    members:
      - andreyjv
      - peteshielded
      - shieldedmark
  - name: minokawa-maintainers
    maintainers:
      - kmillikin
    members:
      - bobblessinghartley
      - chrisferry
      - dybvig
      - JosephDenman
      - leszek-shielded
      - pataei
  - name: security-managers
    maintainers:
      - bobblessinghartley
    members:
      - dybvig
      - kmillikin
repositories:
  - name: compact
    teams:
      lf-staff: maintain
      compact-admins: admin
      compact-maintainers: maintain
      compact-triage: triage
      security-managers: read
    visibility: public
  - name: .github
    teams:
      lf-staff: maintain
      minokawa-maintainers: maintain
      security-managers: read
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      minokawa-maintainers: maintain
      security-managers: read
    visibility: public
