teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - christinaharter
      - jwagantall
      - minyu66
      - thelinuxfoundation
  - name: minokawa-maintainers
    maintainers:
      - kmillikin
    members:
      - leszek-shielded
      - pataei
      - dybvig
      - JosephDenman
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      minokawa-maintainers: maintain
    visibility: public
