teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - christinaharter
      - jwagantall
      - minyu66
      - thelinuxfoundation
  - name: compact-admins
    maintainers:
      - chrisferry
    members:
      - sgillespie
  - name: compact-maintainers
    maintainers:
      - kmillikin
    members:
      - chrisferry
  - name: minokawa-maintainers
    maintainers:
      - kmillikin
    members:
      - bobblessinghartley
      - chrisferry
      - dybvig
      - JosephDenman
      - leszek-shielded
      - pataei
repositories:
  - name: compact
    teams:
      lf-staff: maintain
      compact-admins: admin
      compact-maintainers: maintain
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      minokawa-maintainers: maintain
    visibility: public
